# 1. Database Connection (The "Address")
spring.datasource.url=jdbc:postgresql://localhost:5432/sih_asset_db
spring.datasource.username=postgres
spring.datasource.password=Rahul@1002
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate Settings (The "Auto-Builder")
# This automatically creates tables in the DB based on your Java code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. App Settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# --- EMAIL CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=systemadminstrator001@gmail.com
spring.mail.password=vfobqtsvhtrpaono
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true